#!/bin/bash

echo "Copy IN/ Copy OUT?"
echo "1 IN"
echo "2 OUT"
read choice
if [ $choice = "1" ]; then
	echo "COPY IN"
	cp ~/.vimrc ./vimrc
	cp ~/.config/Code/User/settings.json ./settings.json
elif [ $choice = "2" ]; then
	echo "COPY OUT"
	cp ./vimrc ~/.vimrc
	cp ./settings.json ~/.config/Code/User/settings.json
else
	echo "Error in Choice"
	exit 1
fi

# Link youtube-dl config
if [ ! -f /etc/youtube-dl.conf ]; then
	echo "Creating youtube-dl config link: /etc/youtube-dl.conf"
	ln -s ./youtube-dl.conf /etc/youtube-dl.conf
else
	echo "File already exists: /etc/youtube-dl.conf"
fi

exit
